### ISSUE TITLE
Not working on wdio 8

### ISSUE THREAD

**Issue by lacell75** [viktor-silakov/wdio-cucumber-viewport-logger-service#1]
I am very interesting by your service but it doesn't work in my side. Could you help me?
I am using chrome with a selenium Grid 4:

```
{
    maxInstances: 4,
    browserName: 'chrome',
    // platformName: 'LINUX',
    acceptInsecureCerts: true,
    'goog:chromeOptions': {
      prefs: {
        'download.default_directory': global.downloadDirChrome,
      },
      // args: ['--no-sandbox', '--disable-gpu', '--disable-extensions', '--headless', '--window-size=1920,1080', '--disable-dev-shm-usage', '--disable-backgrounding-occluded-windows'],
      // args: ['--headless', '--window-size=1920,1080', '--disable-backgrounding-occluded-windows'],
      args: ['--disable-backgrounding-occluded-windows', '--window-size=1980,1080', '--disable-gpu', '--inspect'],
      // extensions: [extensionChrome],
      // w3c: false,
      // args: [
      //  `user-data-dir=${global.userDataChrome}`,
      //  'profile-directory=Profile',
      // ],
    },
  },
```

Please see the logs:

```
@wdio/runner: init remote session
[0-0] 2023-02-03T16:22:11.197Z DEBUG @wdio/utils:initialiseServices: initialise service "intercept" as NPM package
[0-0] 2023-02-03T16:22:11.208Z DEBUG @wdio/utils:initialiseServices: initialise service "cucumber-viewport-logger" as NPM package
[0-0] 2023-02-03T16:22:11.235Z DEBUG @wdio/utils:initialiseServices: initialise service "image-comparison" as NPM package
[0-0] 2023-02-03T16:22:11.383Z DEBUG wdio-cucumber-viewport-logger-service: service options: {
[0-0]   "numberOfSteps": 5,
[0-0]   "enabled": true,
[0-0]   "styles": {
[0-0]           "wrapper": {
[0-0]                   "backgroundColor": "white"
[0-0]           },
[0-0]           "keyword": {
[0-0]                   "color": "red"
[0-0]           },
[0-0]           "text": {
[0-0]                   "fontSize": "30px",
[0-0]                   "color": "green"
[0-0]           },
[0-0]           "closeButton": {
[0-0]                   "color": "red"
[0-0]           }
[0-0]   }
[0-0] }
[0-0] RUNNING in chrome - file:///c:/2-gitlab/end-to-end-tests-wdio/features/test.feature
[0-0] 2023-02-03T16:22:12.719Z DEBUG @wdio/runner: init remote session
[0-0] 2023-02-03T16:22:12.753Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2023-02-03T16:22:13.088Z INFO webdriver: [POST] http://localhost:4444/session
[0-0] 2023-02-03T16:22:13.089Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       acceptInsecureCerts: true,
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     acceptInsecureCerts: true,
[0-0]     'goog:chromeOptions': { prefs: [Object], args: [Array] }
[0-0]   }
[0-0] }
[0-0] 2023-02-03T16:22:14.368Z INFO wdio-image-comparison-service: Adding commands to global browser
[0-0] 2023-02-03T16:22:14.369Z DEBUG @wdio/utils:shim: Finished to run "before" hook in 0ms
[chrome 109.0.5414.120 WINDOWS #0-0] ------------------------------------------------------------------
[chrome 109.0.5414.120 WINDOWS #0-0] Suite started :
[chrome 109.0.5414.120 WINDOWS #0-0]   » c:\2-gitlab\end-to-end-tests-wdio\features\test.feature
[chrome 109.0.5414.120 WINDOWS #0-0] Content-production.03-Quality Issues.20-Adding/deleting/reading comments INQA-262/263
[0-0] 2023-02-03T16:22:23.481Z DEBUG @wdio/utils:shim: Finished to run "beforeFeature" hook in 1ms

[chrome 109.0.5414.120 WINDOWS #0-0] Teardown if preference don't delete for
[0-0] 2023-02-03T16:22:23.559Z DEBUG wdio-cucumber-viewport-logger-service: beforeScenario hook START
[chrome 109.0.5414.120 WINDOWS #0-0] Hook executed :
[0-0] 2023-02-03T16:22:23.560Z DEBUG @wdio/utils:shim: Finished to run "beforeScenario" hook in 1ms
[0-0] 2023-02-03T16:22:23.570Z DEBUG @wdio/utils:shim: Finished to run "beforeStep" hook in 0ms
[0-0] 2023-02-03T16:22:23.571Z INFO webdriver: COMMAND getAlertText()
[0-0] 2023-02-03T16:22:23.574Z INFO webdriver: [GET] http://localhost:4444/session/a2c2f9e8e497bd2499a85c9eff7df5f6/alert/text
[0-0] 2023-02-03T16:22:23.580Z INFO webdriver: COMMAND setTimeouts(undefined, 300000, 300000)
[0-0] 2023-02-03T16:22:23.582Z INFO webdriver: [POST] http://localhost:4444/session/a2c2f9e8e497bd2499a85c9eff7df5f6/timeouts
[0-0] 2023-02-03T16:22:23.582Z INFO webdriver: DATA { pageLoad: 300000, script: 300000 }
[0-0] 2023-02-03T16:22:23.605Z DEBUG webdriver: request failed due to response error: no such alert
[0-0] 2023-02-03T16:22:23.605Z WARN webdriver: Request failed with status 404 due to no such alert
[0-0]   (Session info: chrome=109.0.5414.120)
[0-0] 2023-02-03T16:22:23.607Z INFO webdriver: Retrying 1/2
[0-0] 2023-02-03T16:22:23.608Z INFO webdriver: [GET] http://localhost:4444/session/a2c2f9e8e497bd2499a85c9eff7df5f6/alert/text
[0-0] 2023-02-03T16:22:23.618Z INFO webdriver: RESULT null
[0-0] 2023-02-03T16:22:23.635Z DEBUG webdriver: request failed due to response error: no such alert
[0-0] 2023-02-03T16:22:23.636Z WARN webdriver: Request failed with status 404 due to no such alert
[0-0]   (Session info: chrome=109.0.5414.120)
[0-0] 2023-02-03T16:22:23.637Z INFO webdriver: Retrying 2/2
[0-0] 2023-02-03T16:22:23.638Z INFO webdriver: [GET] http://localhost:4444/session/a2c2f9e8e497bd2499a85c9eff7df5f6/alert/text
[0-0] 2023-02-03T16:22:23.659Z DEBUG webdriver: request failed due to response error: no such alert
[0-0] 2023-02-03T16:22:23.660Z ERROR webdriver: Request failed with status 404 due to no such alert: no such alert
[0-0]   (Session info: chrome=109.0.5414.120)
[0-0] 2023-02-03T16:22:23.669Z INFO webdriver: COMMAND getUrl()
[0-0] 2023-02-03T16:22:23.670Z INFO webdriver: [GET] http://localhost:4444/session/a2c2f9e8e497bd2499a85c9eff7df5f6/url
[0-0] 2023-02-03T16:22:23.686Z INFO webdriver: RESULT data:,
[0-0] Error in "0: Given I am logged on "business-insight" as "end2end.chrom2@gmail.com" with password "pass""
no such alert: no such alert
  (Session info: chrome=109.0.5414.120)
    at getErrorFromResponseBody (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriver/build/utils.js:194:12)
    at NodeJSRequest._request (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/webdriver/build/request/index.js:164:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Browser.wrapCommandFn (file:///C:/2-gitlab/end-to-end-tests-wdio/node_modules/@wdio/utils/build/shim.js:72:29)
[0-0] 2023-02-03T16:22:23.687Z DEBUG @wdio/utils:shim: Finished to run "afterStep" hook in 19ms
```

**Comment by nair-sumesh** [comment]
+1
